<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>fr.damnardev.example</groupId>
		<artifactId>pitest-example-dependencies</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../pitest-example-dependencies/pom.xml</relativePath>
	</parent>

	<artifactId>pitest-example-parent</artifactId>
	<packaging>pom</packaging>

	<name>Pitest Example - Parent</name>
	<description>Parent POM for Pitest Example</description>

	<properties>
		<!-- Java version and encoding -->
		<java.version>21</java.version>
		<encoding>UTF-8</encoding>
		<maven.compiler.release>${java.version}</maven.compiler.release>
		<project.build.sourceEncoding>${encoding}</project.build.sourceEncoding>
		<project.reporting.outputEncoding>${encoding}</project.reporting.outputEncoding>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
				<inherited>false</inherited>
				<executions>
					<execution>
						<id>flatten</id>
						<phase>process-resources</phase>
						<goals>
							<goal>flatten</goal>
						</goals>
						<configuration>
							<updatePomFile>true</updatePomFile>
							<flattenMode>bom</flattenMode>
							<pomElements>
								<parent>keep</parent>
								<properties>keep</properties>
							</pomElements>
						</configuration>
					</execution>
					<execution>
						<id>clean</id>
						<phase>clean</phase>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
